<a href="https://colab.research.google.com/github/shivam110601/human-like-sudoku-solver/blob/main/human_like_sudoku_solver.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import time
import numpy as np

In [9]:
def is_valid(board, row, col, num):
    # Check if the number is already in the row, column, or 3x3 cell group
    if num in board[row, :] or num in board[:, col] or num in board[row//3*3:row//3*3+3, col//3*3:col//3*3+3]:
        return False
    return True

def find_unfilled(board):
    # Find an unfilled cell in the board
    for i in range(9):
        for j in range(9):
            if board[i, j] == 0:
                return i, j
    return None, None

def solve_sudoku(board):
    start_time = time.time()
    while True:
        progress = False
        for i in range(3):
            for j in range(3):
                cell_group = board[i*3:(i+1)*3, j*3:(j+1)*3]
                unfilled_cells = [(x, y) for x in range(i*3, (i+1)*3) for y in range(j*3, (j+1)*3) if board[x, y] == 0]
                unfilled_numbers = set(range(1, 10)) - set(cell_group.flatten())

                for number in unfilled_numbers:
                    possible_positions = []
                    for x, y in unfilled_cells:
                        if is_valid(board, x, y, number):
                            possible_positions.append((x, y))

                    if len(possible_positions) == 1:
                        board[possible_positions[0][0], possible_positions[0][1]] = number
                        progress = True

        if not progress:
            break

    end_time = time.time()  # End time measurement
    solving_time = end_time - start_time
    print(f"Sudoku solved in {solving_time:.4f} seconds.")
    return board

# Example usage:
board = np.array([
    [5, 3, 0, 0, 7, 0, 0, 0, 0],
    [6, 0, 0, 1, 9, 5, 0, 0, 0],
    [0, 9, 8, 0, 0, 0, 0, 6, 0],
    [8, 0, 0, 0, 6, 0, 0, 0, 3],
    [4, 0, 0, 8, 0, 3, 0, 0, 1],
    [7, 0, 0, 0, 2, 0, 0, 0, 6],
    [0, 6, 0, 0, 0, 0, 2, 8, 0],
    [0, 0, 0, 4, 1, 9, 0, 0, 5],
    [0, 0, 0, 0, 8, 0, 0, 7, 9]
])

solved_board = solve_sudoku(board)
print(solved_board)


Sudoku solved in 0.0136 seconds.
[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]
